# Generated by Django 5.2.2 on 2025-06-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='voice_memos/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
                ('llm_response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
